### ISSUE TITLE
Implement ability to group exposed parameters through the GUI

### ISSUE THREAD

**Issue by bbuckley94** [disguise-one/RenderStream-Unity#11]
**Summary:**
It would be nice if we could implement the ability to assign exposed parameters to groups through the GUI. Currently all exposed parameters are placed under the 'Properties' section along with the Scene selection.
The user is able to modify the RenderStreamRemoteParameters script themselves to add custom groups but it would be nice if they could do this through the UI.

**Steps to reproduce:**
1. Create Unity project
2. Add plugin to Assets folder
3. Select a light source
4. Add 'Disguise RenderStream (Remote Parameters)' component
5. Expand 'Fields' and choose options

**Comment by bbuckley94** [comment]
Grouping functionality added to r1.26 in 2c9be2b and 40702a1.

**Comment by husberg-disguise** [comment]
LGTM
