### ISSUE TITLE
Unity stuck on Application.Reload or Compiling Assembly progress bar right after any code changes

### ISSUE THREAD

**Issue by wangyangwang** [disguise-one/RenderStream-Unity#12]
With the plugin in the project. Whenever there is any code change that triggers a recompile, there is a 50% chance Unity will get stuck in that compiling progress bar forever. 

Unity version: 2020.3.3
Plugin : r1.26     e1c3222

**Comment by husberg-disguise** [comment]
I wasn't able to reproduce the exact issue, but fixed a shutdown hang in 06a4a17. 
Let me know if that didn't help and we'll reopen this.

**Comment by husberg-disguise** [comment]
Managed to repro.

Steps to repro:
* Build an executable so RenderStream is loaded
* Play in Editor so Application.Reload is triggered

**Comment by husberg-disguise** [comment]
Hopefully fixed in f05ceea
