### ISSUE TITLE
Rotation not compiling to JSON file during project build

### ISSUE THREAD

**Issue by JWTechnical** [disguise-one/RenderStream-Unity#14]
When setting up the exposed transform for an Object the Rotation is not compiling into the JSON file during a build.

Steps taken:
1. Add an object to the scene
2. Add Renderstream Remote Parameters to object
3. Drag transform from object to Remote parameters
4. Add a group names
5. Build Unity Project

Project Link:
https://www.dropbox.com/sh/oqye4f4rwt8ixh7/AAAsW3iLYRMDIw1QxG15hfLua?dl=0

**Comment by husberg-disguise** [comment]
The transform's rotation is a quaternion, which we don't plan on supporting. The exposed transform itself has position, rotation and scale.

If you want to expose euler angles, write a script in Unity that does the conversion and expose the script's fields.

**Comment by husberg-disguise** [comment]
The field should not be listed if it's not supported though. I raised #15 for hiding all unsupported fields.
