### ISSUE TITLE
Differentiate between exposed objects of the same type

### ISSUE THREAD

**Issue by husberg-disguise** [disguise-one/RenderStream-Unity#4]
If you expose different objects of the same type, the exposed fields will all have the same name making it difficult to know what you're keyframing. Prefix the field's name or category with the object's name so it's easier to differentiate them.

**Comment by husberg-disguise** [comment]
Fixed in r1.26. 

@bbuckley94 Do you want to backport it to r1.25 (r18.1) and r1.23 (r18.0) or leave it until r18.2?

**Comment by bbuckley94** [comment]
I didn't know how to cherry-pick the commit and backport it properly but I've pushed the fix to r1.23 and r1.25 now.
