### ISSUE TITLE
Add de/select all to exposed fields UI 

### ISSUE THREAD

**Issue by husberg-disguise** [disguise-one/RenderStream-Unity#5]
It would be nice if there was a de/select all button at the top of the Fields table within the Remote Parameters component. If you add a component that has many parameters as an Exposed Object and you only wish to expose one or a small subset, it can be annoying having to deselect all the fields you do not want.

**Comment by highlyinteractive** [comment]
Had the same wish. Feel free to implement this, or let me know if you'd prefer a pull request.

    using UnityEngine;
    using UnityEditor;
    using UnityEditorInternal;

    [CustomEditor(typeof(DisguiseRemoteParameters))]
    public class DisguiseRemoteParametersEditor : Editor
    {
        private SerializedProperty _fieldsProp;

        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            serializedObject.Update();

            ReorderableListUtility.DoLayoutListWithFoldout(list);

            GUILayout.BeginHorizontal();
            if (GUILayout.Button("Select All"))
            {
                for (int i = 0; i < _fieldsProp.arraySize; i++)
			    {
                    var element = _fieldsProp.GetArrayElementAtIndex(i);
                    element.FindPropertyRelative("exposed").boolValue = true;
                }
            }
            if (GUILayout.Button("Select None"))
            {
                for (int i = 0; i < _fieldsProp.arraySize; i++)
                {
                    var element = _fieldsProp.GetArrayElementAtIndex(i);
                    element.FindPropertyRelative("exposed").boolValue = false;
                }
            }
            GUILayout.EndHorizontal();

            serializedObject.ApplyModifiedProperties();
        }

        private void OnEnable()
        {
            _fieldsProp = this.serializedObject.FindProperty("fields");
            list = ReorderableListUtility.CreateAutoLayout(_fieldsProp, true, true, false, false);
        }

        private ReorderableList list;
    }

**Comment by husberg-disguise** [comment]
@highlyinteractive Thank you! A PR would be great if you don't mind, so you can get the changeset credit.
