### ISSUE TITLE
'Transform' field written to JSON regardless of exposed value

### ISSUE THREAD

**Issue by bbuckley94** [disguise-one/RenderStream-Unity#8]
**Summary:**
6-DOF object parameters were implemented in r1.26. When adding a Transform component as the 'Exposed Object' in a Remote Parameters component: even if the "Transform" field's Exposed value is set to False, the parameter is written to the JSON file and therefore exposed to d3.

**Bug reduction:**
- Seen with r1.26_beta1.
- Seen regardless of the 'Exposed' value.
- Not seen with any other field. All other fields respect their 'Exposed' value.

**Steps to reproduce:**
1. Create a new Unity project
2. Place plugin the Assets folder
3. Add a new gameobject
4. Add the Remote Parameters component to the gameobject
5. Add the Transform component as the 'Exposed Object' in the Remote Parameters component
6. Disable the 'Transorm' field
7. Build executable
8. Open the JSON file (notice Transform written)

**Comment by husberg-disguise** [comment]
The same will happen for Materials. 

The `exposedObject is <bla>` checks at the top of DisguiseRemoteParameters.exposedParameters are missing `if (fields.Any(field => !field.exposed && field.fieldName == property.displayName))` checks

**Comment by bbuckley94** [comment]
Added the required checks in a57c7a0. If the changes are okay, happy to close this.

**Comment by husberg-disguise** [comment]
LGTM

Could remove the first if with the Debug.Log, but doesn't really matter if it stays.

**Comment by bbuckley94** [comment]
First if removed in 40702a1

**Comment by husberg-disguise** [comment]
LGTM
